### ISSUE TITLE
MVP Iteration 2

### ISSUE THREAD

**Issue by pmrukot** [forcecraft/aion#43]
**Plan**
- [x] Improve UI #32 
- [x] Improve answer evaluation #33 
- [x] Introduce Room model and API #34 
- [x] User profile page #35 
- [x] Form for creating a room #38 
- [x] Form for creating a category #41 
- [x] Form for creating a question #42 
- [x] Handle channel quitting on location change #40

**Comment by pmrukot** [comment]
Closing as all issues has been resolved 🎉 Will open MVP 3 soon.

**Comment by mrapacz** [comment]
@pmrukot instead of opening MVP 3 as an issue you can create a milestone for that. It's easier to filter the issues then.
